### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by honzajavorek**
Updates dependencies.

I was way to eager to close https://github.com/apiaryio/dredd-hooks-template/issues/8. This should actually fix the issue. @gonzalo-bulnes could you please verify these changes are aligned with what you proved worked in Ruby hooks?

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
Hi @honzajavorek! I forgot that too!
The change looks good.

Since these are cross-language templates, I was thinking that maybe a short note in the `README` about updating Aruba (and any other testing tool that would be installed in the future) could be useful to people less familiar with Ruby. Something in the lines of:

```markdown
<!-- README.md -->

## Maintenance

Updating Aruba regularly is not absolutely critical, but helps making sure that all Dredd hooks implementations behave the same.

In order to update your installation and ensure the same version is used accross all your environments, run `bundle update aruba` from time to time and commit the corresponding `Gemfile.lock` as part of the update.
```

(Another possibility is to recommend copying the `Gemfile` and `Gemfile.lock` as part of updating the test suite in the hooks projects, but I like it less because there might be more than Aruba in their `Gemfile`s and the details become tricky.)

What do you think?

**Comment by honzajavorek** [comment]
I like it!

**Comment by gonzalo-bulnes** [comment]
@honzajavorek You can cherry-pick 5f584f22a2 to get the `README` changes if you wish 😉

**Comment by honzajavorek** [comment]
@gonzalo-bulnes The commit somehow became [orphaned](https://help.github.com/articles/commit-exists-on-github-but-not-in-my-local-clone/), so I duplicated it with your authorship. Thanks!

**Comment by honzajavorek** [comment]
I think we should not merge this until https://github.com/apiaryio/dredd-hooks-template/issues/16 gets resolved, because otherwise the test suite would be broken.

**Comment by honzajavorek** [comment]
The test suite has been ported to JavaScript - see https://github.com/apiaryio/dredd-hooks-template/issues/23.

**Pull request closed without merging**
